Testing out new recursion [THEORY STATE]
instead of being asked to input the recursion level, you will input it as a value for the recursion argument. Don't know if it works, will see later.

diff --git a/remuxvideo b/remuxvideo
--- a/remuxvideo
+++ b/remuxvideo
@@ -11,12 +11,21 @@ CYAN='\033[0;36m'
 PURPLE='\033[0;35m'
 NC='\033[0m'
 
-while getopts Dhr flag
+while getopts Dhr: flag
 do
     case $flag in
     D)  destructive=1;;
     h)  printf "Usage \n    h= Display this\n    D= destructive (removes the original file)\n   r= Recursive logic (variable)"; exit;;
-    r)  recurse=1;;
+    r)  recursenum=$OPTARG
+        if [ $recursenum = "i" ] ; then
+            recurse=**/
+        elif [[ $recursenum =~ ^[0-9]+$ ]]; then
+            recurse=$(for i in $(seq $recursenum); do
+                        printf '%s' "*/"
+                    done)
+        else
+        echo -e "${RED}ERROR${NC}   Invalid input for recurse" && echo "Input either a number for recursion level or i for infinite recursion (DANGEROUS!)" && exit 1
+		fi;
     ?)  printf "incorrect usage, use -h for help"; exit;;
     esac
 done
@@ -27,26 +36,6 @@ read from
 echo -e
 echo -e To...
 read to
-
-while true; do
-    if [[ "$recurse" != 1 ]]; then
-        break
-    else
-        recurse=
-        echo -e "${PURPLE}How many times should it recurse? type i for infinite${NC}"
-        read recursenum
-        if [ $recursenum = "i" ] ; then
-            recurse=**/
-            break
-        elif [[ $recursenum =~ ^[0-9]+$ ]]; then
-            recurse=$(for i in $(seq $recursenum); do
-                        printf '%s' "*/"
-                    done)
-            break
-        fi;
-        echo -e "${RED}ERROR${NC}   Invalid input for recurse"
-    fi;
-done
 
 echo
 echo "$recurse"
